%YAML:1.0

# enum camera_type
# {
#     MONOCULAR,
#     STEREO,
#     RGBD,
#     THERMAL,
#     LIDAR,
#     UNKNOWN
# };
imu_topic: "/imu/data"

sensor_list: ['cam_0','cam_1']

cam_0:
  sensor_type: 0
  left_image_topic: "/ros_frame/camera_0"
  frame_id: "cam_0"
  camera_config_file: "/home/yao/vins_depth_ws2/src/MSVIOFrontend/config/MSVIO/cam360/cam_0.yaml"
  extrinsicRotation_imu_camera: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [-2.8833749665917896e-02, -0.014116195676831, -0.99948454110097,
            -0.999573886335575, 0.004954022403771, 0.028766359137359,
            0.00454537366421, 0.999888091038267,  -1.4252893674741474e-02]
  #Translation from camera frame to imu frame, imu^T_cam
  extrinsicTranslation_imu_camera: !!opencv-matrix
    rows: 3
    cols: 1
    dt: d
    data: [-2.9964041980699994e-02, 0.0163323829651326, -4.2422324053882229e-02] 
  #feature traker paprameters
  max_cnt: 200          # max feature number in feature tracking
  min_dist: 20            # min distance between two features
  freq: 13                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
  F_threshold: 1.0        # ransac threshold (pixel)
  show_track: 1           # publish tracking image as topic
  equalize: 1             # if image is too dark or light, trun on equalize to find enough features
  fisheye: 1             # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points
  fisheye_path: "/home/yao/vins_depth_ws2/src/MSVIOFrontend/config/MSVIO/fisheye_mask.jpg"
  image_width: 816
  image_height: 686
  mirror_parameters:
    xi: 1.9370645285718184
  distortion_parameters:
    k1: -0.030101416027143404
    k2: 0.2030609832189508
    p1: -0.00017036850596376823
    p2: -0.0009683462814614623
  projection_parameters:
    fx: 571.1375267362884
    fy: 573.7579044576655
    cx: 417.4754436701555
    cy: 344.6485017643427